---
apiVersion: v1
kind: Service
metadata:
  name: gogs-svc
  labels:
    app: gogs-app
    group: gogs
spec:
  type: NodePort
  selector:
    app: gogs-app
  ports:
  - name: gogs-main
    protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 32300
  - name: gogs-ssh
    port: 22
    protocol: TCP
    targetPort: 22
    nodePort: 32222
  - name: gogs-db
    port: 5432
    protocol: TCP
    targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gogs-app
spec:
  serviceName: gogs-svc
  replicas: 1
  selector:
    matchLabels:
      app: gogs-app
  template:
    metadata:
      labels:
        app: gogs-app
        group: gogs
    spec:
      volumes:
        - name: gogs-data
          persistentVolumeClaim:
            claimName: gogs-pvc
        - name: gogs-bkp
          persistentVolumeClaim:
            claimName: gogsbkp-pvc
        - name: gogsdb-data
          persistentVolumeClaim:
            claimName: gogsdb-pvc
      containers:
      - name: gogsdb
        image: quay.io/ibrandao/gogs-db:latest
        env:
          # define your user and passwords bellow
          ### WARNING ### 
          # consider to use k8s secrets or a password manager instead
          - name: POSTGRES_PASSWORD
            value: "test"
          - name: GOGS_PASSWORD
            value: "test"
          - name: GOGS_USER
            value: "gogs"
          - name: POSTGRES_DB
            value: "gogs"
        ports:
        - containerPort: 5432
          name: gogsdb-port
          protocol: TCP
        volumeMounts:
        - name: gogsdb-data
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            cpu: 500m
            memory: 128Mi 
          limits:
            cpu: 500m
            memory: 256Mi
      - name: gogs
        image: quay.io/ibrandao/gogs:latest
        ports:
        - name: gogs-ui-port
          containerPort: 3000
          protocol: TCP
        - name: gogs-ssh-port
          containerPort: 22
          protocol: TCP
        volumeMounts:
        - name: gogs-data
          mountPath: /data
        - name: gogs-bkp
          mountPath: /backup
        resources:
          requests:
            cpu: 500m
            memory: 512Mi 
          limits:
            cpu: 1000m
            memory: 1024Mi
