---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gogs-pvc
  labels:
    group: gogs
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  storageClassName: local-path
  volumeMode: Filesystem
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gogsdb-pvc
  labels:
    group: gogs
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  storageClassName: local-path
  volumeMode: Filesystem
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gogsbkp-pvc
  labels:
    group: gogs
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  storageClassName: local-path
  volumeMode: Filesystem
status: {}
