#!/bin/env bash
# This script is a demo to backup and restore gogs
# it can be used as an inspiration to create automate backups and restores
# Backup and restore should be easy but some tricks and clean-ups could apear
# this script demonstrates a working version of it with containers
# Some references of common issues can be found from bellow links:
# [Failed to restore in containers because of cross-device-link](https://github.com/gogs/gogs/issues/4339#issuecomment-358339037)
# [Backup and Restore rules](https://github.com/gogs/gogs/discussions/6876)

arg="$1"
file="$2"

case "$arg" in
  backup)
    podman exec --user git gogs_gogs_1 ./gogs backup --target /backup
  ;;
  restore)
    # some clean-ups must be done in order to full restore gogs
    # the actions are:
    # 1. create the tmp directory to extract the temp zip avoiding the cross-device-link error
    # 2. clean the gogs-repositories to avoid permissions errors
    # 3. restore the full compressed backup
    # 4. find and remove all .bak directories avoiding it to be backup in the next backup
    # 5. restart gogs daemon
    # 6. remove the temporary restoration directory 
    podman exec --user git gogs_gogs_1 bash -c "mkdir -p /data/tmp; \
      rm -rf /data/git/gogs-repositories; \
      /app/gogs/gogs restore --from "$file" -t /data/tmp/; \
      find /data -type d -name '*.bak' -exec rm -rf {} \+; \
      pkill -HUP gogs; \
      rm -rf /data/tmp"
  ;;
  volbkp)
    # create a tarball of the gogs_bkp volume
    # this will allow to save all backup files into the host
    bkpvol="gogs-bkp-vol-$(date +%Y-%m-%d-%s).tar"
    podman volume export gogs_gogs_bkp -o "${bkpvol}" && bzip2 "${bkpvol}"
    printf "Backup Volume Created: %s\n" "$(pwd)/${bkpvol}.bz2"
    
  ;;
  volrestore)
    # restore a volume backup tarball to the gogs container volume
    # 1. make sure to create the gogs_gogs_bkp first
    # 2. import the volume with volrestore command
    # 3. to list the backup files inside the volume run the list backups command
    podman volume import gogs_gogs_bkp "${file}" && printf "Backup Volume Restored!\n"
  ;;
  list)
    # list all backup files generated by gogs in the backup volume
    printf "To restore those files use the path with /backup/file.zip\n"
    voldata=$(podman volume inspect gogs_gogs_bkp --format "{{.Mountpoint}}")
    ls -lh --color "${voldata}"
  ;;

  *|help)
    echo -e "Usage:
    $0 backup \t\t\t\t\t- Creates a ziped backup file in the /backup volume directory
    $0 restore /backup/file.zip \t\t\t- Restore a backup from the specified path
    $0 volbkp \t\t\t\t\t- Save the gogs backup volume as a tarball file in the host
    $0 volrestore file.tar.bz2 \t\t\t- Restore the gogs backup volume
    $0 list \t\t\t\t\t- List all backup files
    "
  ;;
esac
