#!/bin/ash
set -e

psql -v ON_ERROR_STOP=1 -v PASS="$GOGS_PASSWORD" -v GOGS="$GOGS_USER" -v DB="$POSTGRES_DB" --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER :GOGS WITH PASSWORD :'PASS';
	GRANT ALL PRIVILEGES ON DATABASE :DB TO :GOGS;
EOSQL
